services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    network_mode: host #optional
    environment:
      - PUID=1000 #UPDATE ON RASPBERRY PI
      - PGID=1000 #UPDATE ON RASPBERRY PI
      - TZ=Etc/UTC #optional
      - SUBDOMAINS=connormorrison
      - TOKEN=c62e6ab4-dd8a-4f75-9b14-09cd51578e11
      - UPDATE_IP=ipv4 #optional
      - LOG_FILE=false #optional
    volumes:
      - /path/to/duckdns/config:/config #optional
    restart: unless-stopped

  alpine-api-gateway:
    build: 
      context: ./alpine-api-gateway
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - game-service
    networks:
      - my-network

  game-service:
    build:
      context: ./game-service
    ports:
      - "8000:8000"
    volumes:
      - ./game-service:/app
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
